# Note: This recipe currently only works on OS X and Linux. Furthermore, on OS
# X, it is built with --without-x (terminal emacs only). Feel free to lift
# either of these restrictions if you are able to get it to build.

{% set version = "25.1" %}

package:
  name: emacs
  version: {{ version }}

source:
  fn: emacs-{{ version }}.tar.xz
  url: http://ftp.gnu.org/gnu/emacs/emacs-{{ version }}.tar.xz
  sha1: 983e457971e3e3c8964d039c113033f98132b8a8

build:
  number: 3
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libxml2
    - ncurses 5.9*
    - dbus  # [osx]
    - jpeg 9*
    - libpng >=1.6.23,<1.7
    - libtiff 4.0.*
    - giflib 5.1.*
    - freetype 2.6.*  # [linux]
  run:
    - libxml2
    - ncurses 5.9*
    - dbus  # [osx]
    - jpeg 9*
    - libpng >=1.6.23,<1.7
    - libtiff 4.0.*
    - giflib 5.1.*
    - freetype 2.6.*  # [linux]

test:
  commands:
    - $PREFIX/bin/emacs --help

    # This test fails on CircleCI because there is no tty.
    - $PREFIX/bin/emacs --kill  # [not linux]

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL-3.0
  summary: 'GNU Emacs is an extensible, customizable text editor.'
  license_file: COPYING

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
