# Note: This recipe currently only works on OS X and Linux.

{% set version = "27.1" %}

package:
  name: emacs
  version: {{ version }}

source:
  fn: emacs-{{ version }}.tar.xz
  url: http://ftp.gnu.org/gnu/emacs/emacs-{{ version }}.tar.xz
  sha256: 4a4c128f915fc937d61edfc273c98106711b540c9be3cd5d2e2b9b5b2f172e41
  patches:
   - 0001-apple-silicon-configure.patch  # [osx]
   - 0002-apple-silicon-resign-binary.patch  # [osx]
   - 0003-apple-silicon-cross-compile-configure.patch  # [osx and build_platform != target_platform]
   - 0004-apple-silicon-cross-compile-makefile.patch  # [osx and build_platform != target_platform]
   - 0005-apple-silicon-cross-compile-nextstep-makefile.patch  # [osx and build_platform != target_platform]

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - m4  # [unix]
    - make  # [unix]
    - libxml2  # [build_platform != target_platform]
    - ncurses  # [build_platform != target_platform]
    - dbus  # [build_platform != target_platform]
    - jpeg  # [build_platform != target_platform]
    - libpng  # [build_platform != target_platform]
    - libtiff  # [build_platform != target_platform]
    - librsvg  # [build_platform != target_platform]
    - giflib  # [build_platform != target_platform]
    - gnutls  # [build_platform != target_platform]
    - gmp  # [build_platform != target_platform]
    - glib  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
  host:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - librsvg
    - giflib
    - gnutls
    - gmp
    - glib
    - freetype        # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - zlib

  run:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - giflib
    - gnutls
    - gmp
    - glib
    - freetype        # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - zlib

test:
  commands:
    - $PREFIX/bin/emacs --help
    - $PREFIX/bin/emacsclient --help
    - $PREFIX/bin/ctags --help
    - $PREFIX/bin/ebrowse --help
    - $PREFIX/bin/etags --help
    - $PREFIX/bin/emacs -nw -Q --kill --batch

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL-3.0-only
  summary: 'GNU Emacs is an extensible, customizable text editor.'
  license_file: COPYING

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - notestaff
