# Note: This recipe currently only works on OS X and Linux.

{% set version = "29.3" %}

# Version of GCC sources used to build the embedded JIT compiler
{% set gcc_version = "14.2.0" %}

package:
  name: emacs
  version: {{ version }}

source:
  - fn: emacs-{{ version }}.tar.xz
    url: http://ftp.gnu.org/gnu/emacs/emacs-{{ version }}.tar.xz
    sha256: c34c05d3ace666ed9c7f7a0faf070fea3217ff1910d004499bd5453233d742a0
    patches:
      - 0001-disable-sanity-check.patch  # [osx and build_platform != target_platform]
      - 0002-apple-silicon-resign-binary.patch  # [osx]
      - 0003-macos-cross-compile-configure.patch  # [osx and build_platform != target_platform]
      - 0004-macos-cross-compile-makefile.patch  # [osx and build_platform != target_platform]
      - 0005-macos-cross-compile-nextstep-makefile.patch  # [osx and build_platform != target_platform]
      - 0006-macos-cross-compile-post-install-pdump-path.patch  # [osx and build_platform != target_platform]
      - 0007-macos-cross-compile-lisp-makefile.patch  # [osx and build_platform != target_platform]
  - fn: gcc-{{ gcc_version }}.tar.xz  # [linux]
    url: https://ftp.gnu.org/gnu/gcc/gcc-{{ gcc_version }}/gcc-{{ gcc_version }}.tar.xz  # [linux]
    sha256: a7b39bc69cbf9e25826c5a60ab26477001f7c08d85cec04bc0e29cabed6f3cc9  # [linux]
    folder: gcc  # [linux]

build:
  number: 2
  skip: true  # [win]
  ignore_prefix_files:
    - lib/emacs/jit/bin/*
    - lib/emacs/jit/lib/*

requirements:
  build:
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # [linux]
    - {{ stdlib("c") }}
    - autoconf  # [unix]
    - automake  # [unix]
    - m4  # [unix]
    - make  # [unix]
    - gtk3  # [build_platform != target_platform]
    - harfbuzz  # [build_platform != target_platform]
    - libxml2  # [build_platform != target_platform]
    - ncurses  # [build_platform != target_platform]
    - dbus  # [build_platform != target_platform]
    - libjpeg-turbo   # [build_platform != target_platform]
    - libpng  # [build_platform != target_platform]
    - libtiff  # [build_platform != target_platform]
    - librsvg  # [build_platform != target_platform]
    - giflib  # [build_platform != target_platform]
    - gnutls  # [build_platform != target_platform]
    - gmp  # [build_platform != target_platform]
    - glib  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
    - liblzma-devel
    - libtree-sitter
    - jansson
    - texinfo

  host:
    - {{ stdlib("c") }}  # [linux]
    - binutils  # [linux]
    - libxml2
    - ncurses
    - dbus  # [osx]
    - libjpeg-turbo
    - libpng
    - libtiff
    - liblzma-devel
    - librsvg
    - giflib
    - gnutls
    - gmp
    - mpc  # [linux]
    - mpfr  # [linux]
    - glib
    - freetype  # [linux]
    - cairo  # [linux]
    - gtk3  # [linux]
    - harfbuzz  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-xorgproto  # [linux]
    - xorg-libxtst  # [linux]
    - zlib
    - libtree-sitter
    - jansson

  run:
    - binutils  # [linux]
    - libxml2
    - ncurses
    - dbus  # [osx]
    - libjpeg-turbo
    - libpng
    - libtiff
    - giflib
    - gnutls
    - gmp
    - glib
    - freetype  # [linux]
    - cairo  # [linux]
    - gtk3  # [linux]
    - harfbuzz  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-xorgproto  # [linux]
    - xorg-libxtst  # [linux]
    - zlib
    - libtree-sitter
    - jansson

test:
  commands:
    - $PREFIX/bin/emacs --help
    - $PREFIX/bin/emacsclient --help
    - $PREFIX/bin/ctags --help
    - $PREFIX/bin/ebrowse --help
    - $PREFIX/bin/etags --help
    - $PREFIX/bin/emacs -nw -Q --kill --batch
    - $PREFIX/bin/emacs -Q --kill --batch
    # Make sure treesit works
    - $PREFIX/bin/emacs --batch --eval '(unless (treesit-available-p) (kill-emacs 1))'
    # Make sure json works
    - $PREFIX/bin/emacs --batch --eval '(unless (json-available-p) (kill-emacs 1))'
    - $PREFIX/bin/emacs --batch --eval '(batch-native-compile t)' $PREFIX/share/emacs/{{ version }}/lisp/calculator.elc  # [linux]

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL-3.0-only
  summary: GNU Emacs is an extensible, customizable text editor.
  license_file: COPYING

extra:
  recipe-maintainers:
    - asmeurer
    - jmakovicka
    - msarahan
    - notestaff
