# Note: This recipe currently only works on OS X and Linux. Furthermore, on OS
# X, it is built with --without-x (terminal emacs only). Feel free to lift
# either of these restrictions if you are able to get it to build.

{% set version = "25.3" %}

package:
  name: emacs
  version: {{ version }}

source:
  fn: emacs-{{ version }}.tar.xz
  url: http://ftp.gnu.org/gnu/emacs/emacs-{{ version }}.tar.xz
  sha1: 1cb4f39e9c0a3305fd62f936c7c95ff8e2924323

build:
  number: 2
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - giflib
    - freetype        # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - zlib
    - python        # [osx]
  run:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - giflib
    - freetype        # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - zlib

test:
  commands:
    - $PREFIX/bin/emacs --help
    - $PREFIX/bin/emacsclient --help
    - $PREFIX/bin/ctags --help
    - $PREFIX/bin/ebrowse --help
    - $PREFIX/bin/etags --help
    - $PREFIX/bin/emacs -nw -Q --kill --batch

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL-3.0
  summary: 'GNU Emacs is an extensible, customizable text editor.'
  license_file: COPYING

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - notestaff
