# Note: This recipe currently only works on OS X and Linux.

{% set version = "29.2" %}

package:
  name: emacs
  version: {{ version }}

source:
  fn: emacs-{{ version }}.tar.xz
  url: http://ftp.gnu.org/gnu/emacs/emacs-{{ version }}.tar.xz
  sha256: 7d3d2448988720bf4bf57ad77a5a08bf22df26160f90507a841ba986be2670dc
  patches:
    - 0001-disable-sanity-check.patch  # [osx and build_platform != target_platform]
    - 0002-apple-silicon-resign-binary.patch  # [osx]
    - 0003-macos-cross-compile-configure.patch  # [osx and build_platform != target_platform]
    - 0004-macos-cross-compile-makefile.patch  # [osx and build_platform != target_platform]
    - 0005-macos-cross-compile-nextstep-makefile.patch  # [osx and build_platform != target_platform]
    - 0006-macos-cross-compile-post-install-pdump-path.patch  # [osx and build_platform != target_platform]
    - 0007-macos-cross-compile-lisp-makefile.patch  # [osx and build_platform != target_platform]

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - autoconf  # [unix]
    - automake  # [unix]
    - m4  # [unix]
    - make  # [unix]
    - gtk3  # [build_platform != target_platform]
    - harfbuzz  # [build_platform != target_platform]
    - libxml2  # [build_platform != target_platform]
    - ncurses  # [build_platform != target_platform]
    - dbus  # [build_platform != target_platform]
    - libjpeg-turbo   # [build_platform != target_platform]
    - libpng  # [build_platform != target_platform]
    - libtiff  # [build_platform != target_platform]
    - librsvg  # [build_platform != target_platform]
    - giflib  # [build_platform != target_platform]
    - gnutls  # [build_platform != target_platform]
    - gmp  # [build_platform != target_platform]
    - glib  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
    - libtree-sitter
    - jansson
    - gcc  # [linux]

  host:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - libjpeg-turbo
    - libpng
    - libtiff
    - librsvg
    - giflib
    - gnutls
    - gmp
    - glib
    - freetype  # [linux]
    - cairo  # [linux]
    - gtk3  # [linux]
    - harfbuzz  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-xineramaproto  # [linux]
    - xorg-libxtst  # [linux]
    - zlib
    - libtree-sitter
    - jansson
    - gcc  # [linux]

  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - libxml2
    - ncurses
    - dbus  # [osx]
    - libjpeg-turbo
    - libpng
    - libtiff
    - giflib
    - gnutls
    - gmp
    - glib
    - freetype  # [linux]
    - cairo  # [linux]
    - gtk3  # [linux]
    - harfbuzz  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxi  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxcomposite  # [linux]
    - xorg-libxdamage  # [linux]
    - xorg-libxinerama  # [linux]
    - xorg-xineramaproto  # [linux]
    - xorg-libxtst  # [linux]
    - zlib
    - libtree-sitter
    - jansson
    - gcc  # [linux]

test:
  commands:
    - $PREFIX/bin/emacs --help
    - $PREFIX/bin/emacsclient --help
    - $PREFIX/bin/ctags --help
    - $PREFIX/bin/ebrowse --help
    - $PREFIX/bin/etags --help
    - $PREFIX/bin/emacs -nw -Q --kill --batch
    - $PREFIX/bin/emacs -Q --kill --batch
    # Make sure treesit works
    - $PREFIX/bin/emacs --batch --eval '(unless (treesit-available-p) (kill-emacs 1))'
    # Make sure json works
    - $PREFIX/bin/emacs --batch --eval '(unless (json-available-p) (kill-emacs 1))'
    # Make sure native compilation works
    - $PREFIX/bin/emacs --batch --eval '(unless (native-comp-available-p) (kill-emacs 1))'  # [linux]

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL-3.0-only
  summary: GNU Emacs is an extensible, customizable text editor.
  license_file: COPYING

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - notestaff
