build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: alma9
provider:
  linux: azure
  osx: azure
test: native_and_emulated
