travis:
  secure:
    BINSTAR_TOKEN: Ldn62CbBaB6j9rU/U0bX+H4sW7FpPHd76tyU92/lHpdn81uv1TLGKmyQIE1RLrH3Q3YbLOH88n3Qzbbt6MmV8U366ZnhFWkXc37unl2ezUUsRk0FkuZX3I2FhzwM5Fjb0Ue+DIoYouTs9Q1WuS/ZsH6eG0hfphNANg2Xexs6v5MIRjAg8Gc4l8PBA54FP98b3H2r9gO0MaefTKCKZbsuI9YeuXWK6I6EDMmM5QntZtCw7DMAwEM56KqRHGFDyjZ5pETfw77++hr+YtdVOVSgOUpCzhWu1kGdvVbe7f0tYnm6iQ4BlVZTOuWpY6K2MMWpzneR9YFlie03kFGmLPujRRBbWRShbuynxSaV0lQEauXm5c2GqK+PqKP2vDYENECjXPAmXyB8iYifqCo/7b9VjjW+eGklKvwtMPeb51DU7f6Ju107y6qb7KK9dAf8lP3X5MNfAf6IJ3CL3Fv7m5jx6RDiyI3acLvvRyyQ1TjrX5EcXWRGuyzsdDxDKifZSTjsiYz4B+DryM2rkXBjvOmKhpahZYTvQ9TPrIVYEgtT9dYMj8sL4qBYcO2/ZSdc0Ji2TpGveRm46OxKEf2SvAtICpkRxH38U1kwzvACpkQBuSr9M64QlHqDWfxP9/HBPbM1reuEmaxMDE12s37TeU0hq8l3vlLF7+f5AKLZHwpW6sE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
